name: Check

on:
  push:
    branches: []
  pull_request:
    branches: []
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: npm-${{ hashFiles('package.json') }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Check
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: npm-${{ hashFiles('package.json') }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Check
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: npm-${{ hashFiles('package.json') }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Check
        run: npm run format
